"""Changes to routine and userworkout models

Revision ID: 5efeb3befb86
Revises: 
Create Date: 2024-05-03 16:21:04.249557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5efeb3befb86'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routine', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('workout_id')

    with op.batch_alter_table('user_workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('routine_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'routine', ['routine_id'], ['id'])

    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.alter_column('secondaryMuscles',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.JSON(),
               existing_nullable=False)
        batch_op.alter_column('instructions',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.JSON(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.alter_column('instructions',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)
        batch_op.alter_column('secondaryMuscles',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    with op.batch_alter_table('user_workout', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('routine_id')

    with op.batch_alter_table('routine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workout_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'workout', ['workout_id'], ['id'])

    # ### end Alembic commands ###
